### ISSUE TITLE
setAliveCheck(true) flag hangs the execution.

### ISSUE THREAD

**Issue by bhargavmist** [gwhalin/Memcached-Java-Client#22]
Hi,

I am trying to use the setAliveCheck(true) flag so that when a memcacheD server goes down, the flag makes the client check for the connection and if not available then failover to the next server. During my execution I noticed that it hangs the application and the appln does nothing. I am trying to use the client with SASL support.

Thanks.

here is my code snippet:

```
    SchoonerSockIOPool pool = null;
    try {
                    pool = SchoonerSockIOPool.getInstance("default", AuthInfo.typical("cacheuser", "password"));
                    pool.setServers( servers );
                    pool.setWeights( weights );
                    pool.setInitConn( 10 );
                    pool.setMinConn( 5 );
                    pool.setMaxConn( 250 );
                    pool.setMaintSleep( 10 );
                    pool.setNagle( false );
                    pool.setSocketTO( readTO );
                    pool.setSocketConnectTO( 0 );
                    pool.setMaxIdle( maxIdle );
```

//                        pool.setAliveCheck(true);
                        pool.setFailback(true);
                        pool.setFailover(true);
                        pool.initialize();
                } catch (Exception e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();

Thanks.

**Comment by mengli** [comment]
Hi bhargavmist,

Please don't use "pool.setAliveCheck(true)", it hanges the client. I have fixed this issue. Please check out the latest source code and have a try.

Meng Lee

**Comment by bhargavmist** [comment]
Hi Meng,

The code files on the main page still shows old dates, is that the latest code ? How do i check out latest code ? 

Thanks.

**Comment by mengli** [comment]
Hi bhargavmist,

Version 2.6.1 is under performance branch, not the master branch. 
So please open this url: https://github.com/gwhalin/Memcached-Java-Client/tree/performance
Then click "Downloads" button in the top right corner, and then click "Download .zip" under the download source menu.

If you still have any problem, feel free to let me know

Meng Lee

**Comment by bhargavmist** [comment]
Hi mengli,

Thank you for your response, I was able to download the code and test it but
looks like now I am getting OutOfMemory exception.

when i am using the new code I get

java.lang.OutOfMemoryError
at java.nio.DirectByteBuffer.(DirectByteBuffer.java:126)

error.

Following is my code:

SchoonerSockIOPool pool = null;

```
try {
    pool = SchoonerSockIOPool.getInstance("test",
```

AuthInfo.typical("cacheuser", "password"));
        pool.setServers(serverlist);

```
    pool.setInitConn(10);
    pool.setMinConn(5);
    pool.setMaxConn(250);
    pool.setNagle(false);
    pool.setSocketTO( 3000 );
    pool.setSocketConnectTO( 0 );
    pool.setMaxIdle( 1000 * 60 * 60 * 6 );

    pool.setFailback(true);
    pool.setFailover(true);

    pool.initialize();

    mcc = new MemCachedClient("test", true, true);

} catch (Exception e) {
    System.out.println("Exception while initializing the pool : "
```
- e.getMessage());
  
  }

Following is the full stack trace:

java.lang.OutOfMemoryError
at java.nio.DirectByteBuffer.(DirectByteBuffer.java:126)
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
at
com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.(SchoonerSockIOPool.java:1364)
at
com.schooner.MemCached.SchoonerSockIOFactory.createSocket(SchoonerSockIOFactory.java:76)
at
com.schooner.MemCached.AuthSchoonerSockIOFactory.makeObject(AuthSchoonerSockIOFactory.java:45)
at
org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
at
com.schooner.MemCached.SchoonerSockIOPool.getConnection(SchoonerSockIOPool.java:547)
at
com.schooner.MemCached.SchoonerSockIOPool.getSock(SchoonerSockIOPool.java:485)
at com.schooner.MemCached.BinaryClient.set(BinaryClient.java:368)
at com.schooner.MemCached.BinaryClient.add(BinaryClient.java:256)
at com.danga.MemCached.MemCachedClient.add(MemCachedClient.java:709)
at
com.qpass.usersecurity.memcacheD.JavaMemcacheDClient.add(JavaMemcacheDClient.java:84)
at
com.qpass.usersecurity.memcacheD.JavaMemcacheDClientTest.singleTest(JavaMemcacheDClientTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:592)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:21)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:194)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:53)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:185)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at
org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:142)
at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:592)
at
org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
at
org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)

It was working fine with the 2.6.1 release.

Can you pls help.

Thanks.

**Comment by mengli** [comment]
Hi,
Here max connection number is too large, are you sure you need some many pooled connections?
pool.setMaxConn(250);

comment this line out, don't use this api again, the connection pool will maintain it for you.
pool.setMaxIdle( 1000 \* 60 \* 60 \* 6 );

Meng Lee

**Comment by bhargavmist** [comment]
Hi mengli,

So here is what i understand, the client maintains one dedicated connection
to one server in the server list correct?

e.g. if we have 2 servers in the server list then the client will maintain
two tcp connections right ?

Thanks.

**Comment by bhargavmist** [comment]
Hi mengli,

My JVM is currently set to -Xmx1500m and now i am using pool.setMaxConn(5)
to 5 and i am still getting the same exception.

Thanks.
