### ISSUE TITLE
Out Of Memory, when host fails.

### ISSUE THREAD

**Issue by tootedom** [gwhalin/Memcached-Java-Client#5]
I've just been running some tests on 2.5.0, to investigate the binary protocol, and I've hit an Out of Memory exception that occurs if a node failure is simulated, while the application is running, i.e.:
- start memcached daemon
- write key
- running 500 get() on key
- stop daemon
- runing 500 more get() on key

During the second lot of 500 get() you will recieve an OOM:

<pre>
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:633)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:95)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288)
    at com.schooner.MemCached.SchoonerSockIO.<init>(SchoonerSockIO.java:51)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(SchoonerSockIOPool.java:1369)
    at com.schooner.MemCached.SchoonerSockIOPool.createSocketWithAdd(SchoonerSockIOPool.java:404)
    at com.schooner.MemCached.SchoonerSockIOPool.getConnection(SchoonerSockIOPool.java:545)
    at com.schooner.MemCached.SchoonerSockIOPool.getSock(SchoonerSockIOPool.java:480)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:1519)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:750)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:746)
    at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)
</pre>

Looking at the code, it seems to be coming from the ByteBuffer.allocateDirect in the SchoonerSockIO, constructor.   The following patch in SchoonerSockIOPool.java (1375), seems to sort it out:

from

<pre>
sock = getSocket(ip[0], Integer.parseInt(ip[1]), connectTimeout);
</pre>

to

<pre>
// get socket: default is to use non-blocking connect
try
{
    sock = getSocket(ip[0], Integer.parseInt(ip[1]), connectTimeout);
}
catch(Exception e)
{           
    writeBuf.clear();
    writeBuf = null;
    throw new IOException(e);
}
</pre>

Seems to sort it out; but not sure if that causes any other issues.

Sorry if this post is messy, not sure of the markup to be used.
/dom

**Comment by mengli** [comment]
Hi tootedom,

Thanks very much for trying our new version of memcached client.

We have fixed this bug. It is cause by wrong connection pool maintenance strategy.

Thanks again for giving us the useful information of this new version.

**Comment by tootedom** [comment]
Hi mengli,

Thanks for the update.  I've pulled down the latest changes from git, and ran my test again; I still see the same issue (the same occurs if you use the ascii connection).

<pre>
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:633)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:95)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288)
    at com.schooner.MemCached.SchoonerSockIO.<init>(SchoonerSockIO.java:51)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(SchoonerSockIOPool.java:1369)
    at com.schooner.MemCached.SchoonerSockIOPool.createSocket(SchoonerSockIOPool.java:385)
    at com.schooner.MemCached.SchoonerSockIOPool.getConnection(SchoonerSockIOPool.java:547)
    at com.schooner.MemCached.SchoonerSockIOPool.getSock(SchoonerSockIOPool.java:479)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:1519)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:750)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:746)
    at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)
    at bbc.forge.domt.memcached.whalin.WhalinTest.main(WhalinTest.java:119)
</pre>


I installed your code update into my local maven repo as 2.5.0.2:

<pre>
ant -Dver=2.5.0.2
mv java_memcached-release_2.5.0.2.jar memcached-2.5.0.2.jar
mvn install:install-file  -Dfile=memcached-2.5.0.2.jar -DgroupId=com.whalin -DartifactId=memcached -Dversion=2.5.0.2 -Dpackaging=jar -DgeneratePom=true
</pre>


Here's my test code, to replicate the issue.  I'm using the inmemory mecached daemon jmemcached; however I've verified with memcached 1.4.4, instance on my linux vm; that it's not just an issue with communicating with jmemcached (which can be troublesome at times):

pom.xml

<pre>
&lt;project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"&gt;
    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
    &lt;groupId&gt;bbc.forge.domt&lt;/groupId&gt;
    &lt;artifactId&gt;gwhalin-test&lt;/artifactId&gt;
    &lt;packaging&gt;jar&lt;/packaging&gt;
    &lt;version&gt;1.0.1-SNAPSHOT&lt;/version&gt;
    &lt;name&gt;UrlFetcher-Loader&lt;/name&gt;
    &lt;description&gt;Simple Testing of Whalin memcached&lt;/description&gt;
    &lt;url&gt;http://maven.apache.org&lt;/url&gt;
    &lt;dependencies&gt;
        
        &lt;dependency&gt;
            &lt;groupId&gt;junit&lt;/groupId&gt;
            &lt;artifactId&gt;junit&lt;/artifactId&gt;
            &lt;version&gt;4.4&lt;/version&gt;
            &lt;scope&gt;test&lt;/scope&gt;
        &lt;/dependency&gt;

        
        &lt;dependency&gt;
            &lt;groupId&gt;org.slf4j&lt;/groupId&gt;
            &lt;artifactId&gt;slf4j-log4j12&lt;/artifactId&gt;
            &lt;version&gt;1.5.2&lt;/version&gt;
        &lt;/dependency&gt;
        
        &lt;dependency&gt;
            &lt;groupId&gt;com.thimbleware.jmemcached&lt;/groupId&gt;
            &lt;artifactId&gt;jmemcached-core&lt;/artifactId&gt;
            &lt;version&gt;0.9&lt;/version&gt;
        &lt;/dependency&gt; 
        
        &lt;dependency&gt;
            &lt;groupId&gt;com.whalin&lt;/groupId&gt;
            &lt;artifactId&gt;memcached&lt;/artifactId&gt;
            &lt;version&gt;2.5.0.2&lt;/version&gt;
        &lt;/dependency&gt;

        
    &lt;/dependencies&gt;
    
    &lt;build&gt;
        &lt;plugins&gt;
            &lt;plugin&gt;
                &lt;artifactId&gt;maven-compiler-plugin&lt;/artifactId&gt;
                &lt;configuration&gt;
                    &lt;source&gt;1.6&lt;/source&gt;
                    &lt;target&gt;1.6&lt;/target&gt;
                &lt;/configuration&gt;
            &lt;/plugin&gt;
            &lt;plugin&gt;
                &lt;groupId&gt;org.apache.maven.plugins&lt;/groupId&gt;
                &lt;artifactId&gt;maven-assembly-plugin&lt;/artifactId&gt;
                &lt;configuration&gt;
                    &lt;descriptorRefs&gt;
                        &lt;descriptorRef&gt;jar-with-dependencies&lt;/descriptorRef&gt;
                    &lt;/descriptorRefs&gt;
                    &lt;archive&gt;
                        &lt;manifest&gt;
                            &lt;mainClass&gt;bbc.forge.domt.memcached.whalin.WhalinTest&lt;/mainClass&gt;
                            &lt;packageName&gt;bbc.forge.domt.memcached.whalin&lt;/packageName&gt;
                        &lt;/manifest&gt;
                    &lt;/archive&gt;
                &lt;/configuration&gt;
                &lt;executions&gt;
                    &lt;execution&gt;
                        &lt;id&gt;make-assembly&lt;/id&gt;
                        &lt;!-- this is used for inheritance merges --&gt;
                        &lt;phase&gt;package&lt;/phase&gt;
                        &lt;!-- append to the packaging phase. --&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;single&lt;/goal&gt;
                            &lt;!-- goals == mojos --&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                &lt;/executions&gt;
                
            &lt;/plugin&gt;
        &lt;/plugins&gt;
        
    &lt;/build&gt;
    
&lt;/project&gt;

</pre>


And the replication code is:

bbc.forge.domt.memcached.whalin.WhalinTest.java

<pre>
package bbc.forge.domt.memcached.whalin;

import java.io.Serializable;
import java.net.InetSocketAddress;

import com.danga.MemCached.MemCachedClient;
import com.danga.MemCached.SockIOPool;
import com.thimbleware.jmemcached.CacheImpl;
import com.thimbleware.jmemcached.MemCacheDaemon;
import com.thimbleware.jmemcached.storage.hash.ConcurrentLinkedHashMap;

public class WhalinTest {

    // create a static client as most installs only need
    // a single instance

    // set up connection pool once at class load
    static {
    

    }

    static MemCacheDaemon daemon;
    static int memcachedPortNumber = 11211; 
    static ConcurrentLinkedHashMap cacheStorage;
    static boolean binary = true;

    public static void startDaemon()
    {
        daemon = new MemCacheDaemon();
        // max 100 items, max 1MB
        
//      cacheStorage = new LRUCacheStorageDelegate(100, 3024000, 1024000);
//      daemon.setCache(new com.thimbleware.jmemcached.Cache(cacheStorage));
//      
        cacheStorage =  ConcurrentLinkedHashMap.create(ConcurrentLinkedHashMap.EvictionPolicy.LRU, 10, 1024*1024*30);
        daemon.setCache(new CacheImpl(cacheStorage));
        
        daemon.setAddr(new InetSocketAddress("localhost",memcachedPortNumber));
        daemon.setIdleTime(100000);        
        daemon.setBinary(binary);
        daemon.start();
        
        // give the daemon a moment to start
        
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    public static void stopDaemon()
    {
        daemon.stop();
    }
    
    // from here on down, you can call any of the client calls
    public static void main(String[] args) {
        
        startDaemon();

        // server list and weights
        String[] servers =
        {
            "localhost:11211"
        };
    
        //Integer[] weights = { 3, 3, 2 };
    
        // grab an instance of our connection pool
        SockIOPool pool = SockIOPool.getInstance("bob");
    
        // set the servers and the weights
        pool.setServers( servers );
        //pool.setWeights( weights );
    
        // set some basic pool settings
        // 5 initial, 5 min, and 250 max conns
        // and set the max idle time for a conn
        // to 6 hours
        pool.setInitConn( 1 );
        pool.setMinConn( 1 );
        pool.setMaxConn( 1 );
        pool.setMaxIdle( 1000 * 60 * 60 * 6 );
    
        // set the sleep for the maint thread
        // it will wake up every x seconds and
        // maintain the pool size
        pool.setMaintSleep( 30 );
    
        // set some TCP settings
        // disable nagle
        // set the read timeout to 3 secs
        // and don't set a connect timeout
        pool.setNagle( true );
        pool.setSocketTO( 1000 );
        pool.setSocketConnectTO( 0 );
        pool.setFailback(true);
        pool.setFailover(true);
    
        // initialize the connection pool
        pool.initialize();
    
        MemCachedClient mcc = new MemCachedClient("bob",true);  
        // lets set some compression on for the client
        // compress anything larger than 64k
        mcc.setCompressEnable( true );
        mcc.setCompressThreshold( 64 * 1024 );
        mcc.isUseBinaryProtocol();
        
        mcc.set( "foo", (Serializable)"boo" ,10000);
        String bar = (String)(Serializable) mcc.get( "foo" );       
        System.out.println("The value, outside loop:" + bar);
        
        for(int i = 0; i<1000;i++)
        {
            bar = (String)(Serializable) mcc.get( "foo" );      
            System.out.println("The value:" + bar);
            System.out.flush();
            if(bar!=null && !bar.equals("boo")) 
            {
                System.err.println("ERRRRR");
                System.err.flush();
            }
            
            if(i>0 && i%500==0) 
            {
                System.out.println("STOPPING:" + i);
                stopDaemon();
            }
            
            bar = (String) (String)(Serializable)mcc.get( "foo" );      
            System.out.println("The value:" + bar);
            System.out.flush();
            if(bar!=null && !bar.equals("boo")) 
            {
                System.err.println("ERRRRR");
                System.err.flush();
            }
            
        }
        System.exit(0);

    }
    
}

</pre>


Only when I apply the try/catch around the socket connection, and release the memory assigned by the allocateDirect in the SchoonerSockIO construct, does the memory leak no longer appear.

/dom

**Comment by mengli** [comment]
Hi tootedom,

Thanks very much for your detailed information about this issue.

Indeed, yesterday I just modified the source code and check in them in git version control. But the binary package in the download category has not yet been updated. 
Today, I setup the environment and run your test program in my computer using the latest client, OutofMemory exception is not found.
I'm afraid that your are still using the old binary package. Now the binary package has been updated. Could you kindly download it and try it again.

Thanks again for giving us the useful information of this new version.

**Comment by tootedom** [comment]
Hi mengli

I wasn't using the binary package.  I pulled the source for the performance branch, from git:

<pre>
git pull git://github.com/gwhalin/Memcached-Java-Client.git performance
</pre>


and rebuilt the source code:

<pre>
ant -Dver=2.5.0.3
</pre>


which creates:

<pre>
Building jar: /Users/dominict/gitwork/Memcached-Java-Client/java_memcached-release_2.5.0.3.jar
</pre>


Which I then installed into my local maven repo, and used in my test case.

<pre>
dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ mv java_memcached-release_2.5.0.3.jar memcached-2.5.0.3.jar
dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ mvn install:install-file  -Dfile=memcached-2.5.0.3.jar -DgroupId=com.whalin -DartifactId=memcached -Dversion=2.5.0.3 -Dpackaging=jar -DgeneratePom=true
</pre>


I've just noticed the TestCase, java I sent you; was a mangled by the pre, as I didn't escape the xml in the code.  Apologies.  I'll resend.

I'm running the below with a max of 32mb ram (-Xmx32m)

<pre>
package bbc.forge.domt.memcached.whalin;

import java.io.Serializable;
import java.net.InetSocketAddress;

import com.danga.MemCached.MemCachedClient;
import com.danga.MemCached.SockIOPool;
import com.thimbleware.jmemcached.CacheImpl;
import com.thimbleware.jmemcached.MemCacheDaemon;
import com.thimbleware.jmemcached.storage.hash.ConcurrentLinkedHashMap;  

public class WhalinTest {

    // create a static client as most installs only need
    // a single instance

    // set up connection pool once at class load
    static {
    
            
    }

    static MemCacheDaemon daemon;
    static int memcachedPortNumber = 11211; 
    static ConcurrentLinkedHashMap cacheStorage;
    static boolean binary = true;

    public static void startDaemon()
    {
        daemon = new MemCacheDaemon();
        cacheStorage =  ConcurrentLinkedHashMap.create(ConcurrentLinkedHashMap.EvictionPolicy.LRU, 10, 1024*1024*30);
        daemon.setCache(new CacheImpl(cacheStorage));
        
        daemon.setAddr(new InetSocketAddress("localhost",memcachedPortNumber));
        daemon.setIdleTime(100000);        
        daemon.setBinary(binary);
        daemon.start();
        
        // give the daemon a moment to start
        
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    public static void stopDaemon()
    {
        daemon.stop();
    }
    
    // from here on down, you can call any of the client calls
    public static void main(String[] args) {
        
        startDaemon();

        // server list and weights
        String[] servers =
        {
            "localhost:11211"
        };
    
        //Integer[] weights = { 3, 3, 2 };
    
        // grab an instance of our connection pool
        SockIOPool pool = SockIOPool.getInstance("bob");
    
        // set the servers and the weights
        pool.setServers( servers );
        //pool.setWeights( weights );
    
        // set some basic pool settings
        // 5 initial, 5 min, and 250 max conns
        // and set the max idle time for a conn
        // to 6 hours
        pool.setInitConn( 1 );
        pool.setMinConn( 1 );
        pool.setMaxConn( 1 );
        pool.setMaxIdle( 1000 * 60 * 60 * 6 );
    
        // set the sleep for the maint thread
        // it will wake up every x seconds and
        // maintain the pool size
        pool.setMaintSleep( 30 );
    
        // set some TCP settings
        // disable nagle
        // set the read timeout to 3 secs
        // and don't set a connect timeout
        pool.setNagle( true );
        pool.setSocketTO( 1000 );
        pool.setSocketConnectTO( 0 );
        pool.setFailback(true);
        pool.setFailover(true);
    
        // initialize the connection pool
        pool.initialize();
    
        MemCachedClient mcc = new MemCachedClient("bob",true);  
        // lets set some compression on for the client
        // compress anything larger than 64k
        mcc.setCompressEnable( true );
        mcc.setCompressThreshold( 64 * 1024 );
        mcc.isUseBinaryProtocol();
        
        mcc.set( "foo", (Serializable)"boo" ,10000);
        String bar = (String)(Serializable) mcc.get( "foo" );       
        System.out.println("The value, outside loop:" + bar);
        
        for(int i = 0; i&lt;1000;i++)
        {
            bar = (String)(Serializable) mcc.get( "foo" );      
            System.out.println("The value:" + bar);
            System.out.flush();
            if(bar!=null && !bar.equals("boo")) 
            {
                System.err.println("ERRRRR");
                System.err.flush();
            }
            
            if(i&gt;0 && i%500==0) 
            {
                System.out.println("STOPPING:" + i);
                stopDaemon();
                try
                {
                    System.out.println("Sleeping for 5secs, to give daemon change to stop");
                    Thread.sleep(5000);
                    System.out.println("Awake, Daemon should not be running:" + daemon.isRunning());
                }
                catch(Exception e) {}
                
            }
            
            bar = (String) (String)(Serializable)mcc.get( "foo" );      
            System.out.println("The value:" + bar);
            System.out.flush();
            if(bar!=null && !bar.equals("boo")) 
            {
                System.err.println("ERRRRR");
                System.err.flush();
            }  
            
        }
        
        System.out.println("end");
        System.exit(0);
    }
    
}
</pre>


I have tried both the binary package (The binary package contains the binary 2.5.0.jar, even though it's in the 2.5.1 zip.  I also built the source that is distributed in the jar, using the provided ant script).  I also repulled the performance branch source code and recompiled, and I still get:

<pre>
com.schooner.MemCached.SchoonerSockIOPool Tue Mar 02 07:25:56 GMT 2010 - ++++ failed to get SockIO obj for: localhost:11211
The value:null
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:633)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:95)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288)
    at com.schooner.MemCached.SchoonerSockIO.<init>(SchoonerSockIO.java:51)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(SchoonerSockIOPool.java:1368)
    at com.schooner.MemCached.SchoonerSockIOPool.createSocket(SchoonerSockIOPool.java:385)
    at com.schooner.MemCached.SchoonerSockIOPool.getConnection(SchoonerSockIOPool.java:546)
    at com.schooner.MemCached.SchoonerSockIOPool.getSock(SchoonerSockIOPool.java:479)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:1519)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:750)
    at com.schooner.MemCached.BinaryClient.get(BinaryClient.java:746)
    at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)
    at bbc.forge.domt.memcached.whalin.WhalinTest.main(WhalinTest.java:134)
</pre>


I have verified that the line you removed from the src/main/com/schooner/MemCached/SchoonerSockIOPool.java (409) is not longer present in my source code.

<pre>
poolCurrentConn.get(host).decrementAndGet();
</pre>


Which was in the method:

<pre>
protected final SchoonerSockIO createSocketWithAdd(String host) {
</pre>


Which from the stack trace, isn't the createSocket method that is being called:

<pre>
com.schooner.MemCached.SchoonerSockIOPool.createSocket(SchoonerSockIOPool.java:385)
</pre>


Sorry, I'm not trying to be a pain; and I know it looks as though I am.  but I still am getting the OOM.

I've just re-cloned the entire source again (obtained an entire fresh copy of the code), and re-ran the tests, and still see the issue with the OOM appearing.  So I'm not sure what I'm doing wrong; or as to why you are not seeing the OOM.

<pre>
dominic-tootells-macbook-pro-2:mmc dominict$ git clone git://github.com/gwhalin/Memcached-Java-Client.git
Initialized empty Git repository in /Users/dominict/gitwork/mmc/Memcached-Java-Client/.git/
remote: Counting objects: 1175, done.
remote: Compressing objects: 100% (380/380), done.
remote: Total 1175 (delta 515), reused 1010 (delta 453)
Receiving objects: 100% (1175/1175), 2.20 MiB | 664 KiB/s, done.
Resolving deltas: 100% (515/515), done.

dominic-tootells-macbook-pro-2:mmc dominict$ cd Memcached-Java-Client/

dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/performance

dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ git checkout origin/performance
Note: moving to 'origin/performance' which isn't a local branch
If you want to create a new branch from this checkout, you may do so
(now or later) by using -b with the checkout command again. Example:
  git checkout -b <new_branch_name>
HEAD is now at 84c4698... Fix OutofMemory bug when memcached is down.

dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ ant -Dver=2.5.6

dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ mv java_memcached-release_2.5.6.jar memcached-2.5.6.jar

dominic-tootells-macbook-pro-2:Memcached-Java-Client dominict$ mvn install:install-file  -Dfile=memcached-2.5.6.jar -DgroupId=com.whalin -DartifactId=memcached -Dversion=2.5.6 -Dpackaging=jar -DgeneratePom=true
</pre>


/dom

**Comment by grahamoregan** [comment]
hi -i built using dom's code using from origin/performance and i'm seeing the same probs. i ran get() x 1000, then stopped the server and ran again and it threw an OOM. i haven't had time to check all branches, are you sure we're all looking at the same location?

**Comment by mengli** [comment]
Hi tootedom,

I detailed reviewed your comment and I found that your test environment is based on macbook pro.
Could you tell me something more about your test enviroment, such as operating system, jdk version?
Since I don't have macbook, I just run your code on Windows and Linux.  
My test environment is:
1) Windows XP, java version "1.6.0_04"
2) Linux 2.6.31-19-generic, java version "1.6.0_15"

No exception is found in both test cases.

**Comment by tootedom** [comment]
Hi mengli,

I tested an obtained the same error on multiple environments, If I have time later on I'll run it on a windows machine too:

Here are the environments I've tested it on.

Mac development machine (10.6.2):

dominic-tootells-macbook-pro-2:~ dominict$ uname -a
Darwin dominic-tootells-macbook-pro-2.local 10.2.0 Darwin Kernel Version 10.2.0: Tue Nov  3 10:37:10 PST 2009; root:xnu-1486.2.11~1/RELEASE_I386 i386

dominic-tootells-macbook-pro-2:~ dominict$ java -version
java version "1.6.0_17"
Java(TM) SE Runtime Environment (build 1.6.0_17-b04-248-10M3025)
Java HotSpot(TM) 64-Bit Server VM (build 14.3-b01-101, mixed mode)

Linux Virtual Machine:

[root@pal trunk]# uname -a
Linux pal.sandbox 2.6.18-164.10.1.el5 #1 SMP Thu Jan 7 20:00:41 EST 2010 i686 i686 i386 GNU/Linux

[root@pal trunk]# java -version
java version "1.6.0_05"
Java(TM) SE Runtime Environment (build 1.6.0_05-b13)
Java HotSpot(TM) Client VM (build 10.0-b19, mixed mode, sharing)

[root@pal trunk]# memcached -h
memcached 1.4.4

What code you are running to test the issue?  and what is the actual test case you are running?

**Comment by mengli** [comment]
Hi tootedom,

Sorry for late reply.
These days, we reproduce this bug and analysis it carefully.
We found that it is caused by the network exception when the client can't connect to the server. This exception causes abnormal creation of SockIO and this may cause memory leak of DirectBuffer.

We have fixed these bug and updated both the source code and the binary package.
Could you please try it again?

Hope for your reply.

Thank you very much for your help!

**Comment by tootedom** [comment]
Hi Mengil,

Thanks for the reply back.  I pulled the source, and also downloaded the binary package; and re-ran the testes I have.  I'm no longer getting the Out of Memory with either; so all good.

Thank you very much for investigating and fixing the issue.  
/dom

**Comment by activepxe** [comment]
Hi Im using 2.5.1 release , I still get same OutofMemoryError
aused by: java.lang.OutOfMemoryError
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(Unknown Source)
    at java.nio.ByteBuffer.allocateDirect(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.createSocketWithAdd(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.getConnection(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.getSock(Unknown Source)
    at com.schooner.MemCached.AscIIClient.set(Unknown Source)
    at com.schooner.MemCached.AscIIClient.replace(Unknown Source)
    at com.danga.MemCached.MemCachedClient.replace(Unknown Source)

Is fix available in this release or do I have to pull in a bug fix brnch?
